name: Update existing content

on:
  workflow_dispatch:
  push:
    branches: [trunk]

permissions:
  contents: write
  pull-requests: write

jobs:
  content-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: trunk

      - name: Setup
        uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the content update
        run: |
          sed -i -e "s/image: 'mariadb'/image: 'mariadb:lts'/g" node_modules/@wordpress/env/lib/build-docker-compose-config.js
          chmod -R ugo+w source/wp-content/themes/wporg-main-2022/
          yarn wp-env start
          yarn build:patterns
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: source/wp-content/themes/wporg-main-2022/**/*.php
