name: Translate Strings

on:
  workflow_dispatch:
  push:
    branches:
      - update/generate-i18n-strings
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  translation-strings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: i18n
        uses: WordPress/wporg-repo-tools/.github/actions/i18n@trunk
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no_taxonomies --post_types=page --url=https://wordpress.org/wp-json/wp/v2/ --textdomain=wporg

      - name: Remove the translation context
        run: |
          sed -i "s/, 'page title'//" extra/translation-strings.php
          sed -i "s/_x(/__(/" extra/translation-strings.php

      - name: Commit and push
        # Using a specific hash here instead of a tagged version, for risk mitigation, since this action modifies our repo.
        uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # 1.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: update/generate-i18n-strings
            message: 'Update translation strings'
