name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read # Required to clone the repo.
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packageManager: npm

      - name: Lint
        uses: WordPress/wporg-repo-tools/.github/actions/lint@trunk
