name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: trunk

      - name: Setup
        uses: WordPress/wporg-repo-tools/.github/actions/setup@try/reusable-workflows
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: WordPress/wporg-repo-tools/.github/actions/lint@try/reusable-workflows
